name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubunut-latest
    steps:
      - name: Checkout repostiory code
        uses: action/checkout@v3
      - run: echo "$(cat hello_world.txt)"
